name: neural_inventory_control
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - jupyter
  - tqdm
  - pyyaml
  - pip
  - pip:
    - torch
    - gymnasium
    - gputil